/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.songs;


import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class AppTest {

    @Test
    public void contextLoads() {

    }
}
